syntax = "proto3";

package database;

service DatabaseService {
  rpc GetRecord(GetRecordRequest) returns (GetRecordResponse);
  rpc AddRecord(AddRecordRequest) returns (AddRecordResponse);
  rpc GetSize(GetSizeRequest) returns (GetSizeResponse);
}

message GetRecordRequest {
  int32 index = 1;
}

message GetRecordResponse {
  string record = 1;
}

message AddRecordRequest {
  int32 index = 1;
  string record = 2;
}

message AddRecordResponse {
  bool success = 1;
}

message GetSizeRequest {}

message GetSizeResponse {
  int32 size = 1;
}
